// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counting.proto

package com.example;

public final class Counting {
  private Counting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface sendNumbersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.sendNumbers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 firstValue = 1;</code>
     */
    int getFirstValue();

    /**
     * <code>int32 lastValue = 2;</code>
     */
    int getLastValue();
  }
  /**
   * Protobuf type {@code com.example.sendNumbers}
   */
  public  static final class sendNumbers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.sendNumbers)
      sendNumbersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use sendNumbers.newBuilder() to construct.
    private sendNumbers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private sendNumbers() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new sendNumbers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private sendNumbers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              firstValue_ = input.readInt32();
              break;
            }
            case 16: {

              lastValue_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Counting.internal_static_com_example_sendNumbers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Counting.internal_static_com_example_sendNumbers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Counting.sendNumbers.class, com.example.Counting.sendNumbers.Builder.class);
    }

    public static final int FIRSTVALUE_FIELD_NUMBER = 1;
    private int firstValue_;
    /**
     * <code>int32 firstValue = 1;</code>
     */
    public int getFirstValue() {
      return firstValue_;
    }

    public static final int LASTVALUE_FIELD_NUMBER = 2;
    private int lastValue_;
    /**
     * <code>int32 lastValue = 2;</code>
     */
    public int getLastValue() {
      return lastValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (firstValue_ != 0) {
        output.writeInt32(1, firstValue_);
      }
      if (lastValue_ != 0) {
        output.writeInt32(2, lastValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (firstValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, firstValue_);
      }
      if (lastValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.Counting.sendNumbers)) {
        return super.equals(obj);
      }
      com.example.Counting.sendNumbers other = (com.example.Counting.sendNumbers) obj;

      if (getFirstValue()
          != other.getFirstValue()) return false;
      if (getLastValue()
          != other.getLastValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFirstValue();
      hash = (37 * hash) + LASTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getLastValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.Counting.sendNumbers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.sendNumbers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.sendNumbers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Counting.sendNumbers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.Counting.sendNumbers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Counting.sendNumbers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.Counting.sendNumbers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.sendNumbers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.sendNumbers)
        com.example.Counting.sendNumbersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Counting.internal_static_com_example_sendNumbers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Counting.internal_static_com_example_sendNumbers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Counting.sendNumbers.class, com.example.Counting.sendNumbers.Builder.class);
      }

      // Construct using com.example.Counting.sendNumbers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstValue_ = 0;

        lastValue_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Counting.internal_static_com_example_sendNumbers_descriptor;
      }

      @java.lang.Override
      public com.example.Counting.sendNumbers getDefaultInstanceForType() {
        return com.example.Counting.sendNumbers.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.Counting.sendNumbers build() {
        com.example.Counting.sendNumbers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.Counting.sendNumbers buildPartial() {
        com.example.Counting.sendNumbers result = new com.example.Counting.sendNumbers(this);
        result.firstValue_ = firstValue_;
        result.lastValue_ = lastValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Counting.sendNumbers) {
          return mergeFrom((com.example.Counting.sendNumbers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Counting.sendNumbers other) {
        if (other == com.example.Counting.sendNumbers.getDefaultInstance()) return this;
        if (other.getFirstValue() != 0) {
          setFirstValue(other.getFirstValue());
        }
        if (other.getLastValue() != 0) {
          setLastValue(other.getLastValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Counting.sendNumbers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Counting.sendNumbers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int firstValue_ ;
      /**
       * <code>int32 firstValue = 1;</code>
       */
      public int getFirstValue() {
        return firstValue_;
      }
      /**
       * <code>int32 firstValue = 1;</code>
       */
      public Builder setFirstValue(int value) {
        
        firstValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 firstValue = 1;</code>
       */
      public Builder clearFirstValue() {
        
        firstValue_ = 0;
        onChanged();
        return this;
      }

      private int lastValue_ ;
      /**
       * <code>int32 lastValue = 2;</code>
       */
      public int getLastValue() {
        return lastValue_;
      }
      /**
       * <code>int32 lastValue = 2;</code>
       */
      public Builder setLastValue(int value) {
        
        lastValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lastValue = 2;</code>
       */
      public Builder clearLastValue() {
        
        lastValue_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.sendNumbers)
    }

    // @@protoc_insertion_point(class_scope:com.example.sendNumbers)
    private static final com.example.Counting.sendNumbers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.Counting.sendNumbers();
    }

    public static com.example.Counting.sendNumbers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<sendNumbers>
        PARSER = new com.google.protobuf.AbstractParser<sendNumbers>() {
      @java.lang.Override
      public sendNumbers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new sendNumbers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<sendNumbers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<sendNumbers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.Counting.sendNumbers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface responseNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.responseNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responseValue = 1;</code>
     */
    int getResponseValue();
  }
  /**
   * Protobuf type {@code com.example.responseNumber}
   */
  public  static final class responseNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.responseNumber)
      responseNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use responseNumber.newBuilder() to construct.
    private responseNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private responseNumber() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new responseNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private responseNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responseValue_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Counting.internal_static_com_example_responseNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Counting.internal_static_com_example_responseNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Counting.responseNumber.class, com.example.Counting.responseNumber.Builder.class);
    }

    public static final int RESPONSEVALUE_FIELD_NUMBER = 1;
    private int responseValue_;
    /**
     * <code>int32 responseValue = 1;</code>
     */
    public int getResponseValue() {
      return responseValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseValue_ != 0) {
        output.writeInt32(1, responseValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.Counting.responseNumber)) {
        return super.equals(obj);
      }
      com.example.Counting.responseNumber other = (com.example.Counting.responseNumber) obj;

      if (getResponseValue()
          != other.getResponseValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.Counting.responseNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.responseNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.responseNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.responseNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.responseNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Counting.responseNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Counting.responseNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Counting.responseNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Counting.responseNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.Counting.responseNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.Counting.responseNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.Counting.responseNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.Counting.responseNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.responseNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.responseNumber)
        com.example.Counting.responseNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Counting.internal_static_com_example_responseNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Counting.internal_static_com_example_responseNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Counting.responseNumber.class, com.example.Counting.responseNumber.Builder.class);
      }

      // Construct using com.example.Counting.responseNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseValue_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Counting.internal_static_com_example_responseNumber_descriptor;
      }

      @java.lang.Override
      public com.example.Counting.responseNumber getDefaultInstanceForType() {
        return com.example.Counting.responseNumber.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.Counting.responseNumber build() {
        com.example.Counting.responseNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.Counting.responseNumber buildPartial() {
        com.example.Counting.responseNumber result = new com.example.Counting.responseNumber(this);
        result.responseValue_ = responseValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Counting.responseNumber) {
          return mergeFrom((com.example.Counting.responseNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Counting.responseNumber other) {
        if (other == com.example.Counting.responseNumber.getDefaultInstance()) return this;
        if (other.getResponseValue() != 0) {
          setResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Counting.responseNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Counting.responseNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseValue_ ;
      /**
       * <code>int32 responseValue = 1;</code>
       */
      public int getResponseValue() {
        return responseValue_;
      }
      /**
       * <code>int32 responseValue = 1;</code>
       */
      public Builder setResponseValue(int value) {
        
        responseValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseValue = 1;</code>
       */
      public Builder clearResponseValue() {
        
        responseValue_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.responseNumber)
    }

    // @@protoc_insertion_point(class_scope:com.example.responseNumber)
    private static final com.example.Counting.responseNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.Counting.responseNumber();
    }

    public static com.example.Counting.responseNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<responseNumber>
        PARSER = new com.google.protobuf.AbstractParser<responseNumber>() {
      @java.lang.Override
      public responseNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new responseNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<responseNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<responseNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.Counting.responseNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_sendNumbers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_sendNumbers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_responseNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_responseNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016counting.proto\022\013com.example\"4\n\013sendNum" +
      "bers\022\022\n\nfirstValue\030\001 \001(\005\022\021\n\tlastValue\030\002 " +
      "\001(\005\"\'\n\016responseNumber\022\025\n\rresponseValue\030\001" +
      " \001(\0052V\n\010counting\022J\n\017countingNumbers\022\030.co" +
      "m.example.sendNumbers\032\033.com.example.resp" +
      "onseNumber0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_sendNumbers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_sendNumbers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_sendNumbers_descriptor,
        new java.lang.String[] { "FirstValue", "LastValue", });
    internal_static_com_example_responseNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_responseNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_responseNumber_descriptor,
        new java.lang.String[] { "ResponseValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
